### ISSUE TITLE
Suppress the training output lines

### ISSUE THREAD

**Issue by Ram-N** [JannesKlaas/sometimes_deep_sometimes_learning#1]
This is not an issue per se. But if you look at the notebook, there is one cell where the output is 5000 lines. This makes the Ipynb look much, much larger than it is.

Suggestion is to suppress printing those lines. (Plot win% over time instead.) Thanks much for this work. (Very clear and very useful)

**Comment by JannesKlaas** [comment]
Just pushed a new version with suppressed output, you can now regulate verbosity if you are running the notebook yourself. Thanks for the tip!

**Comment by Ram-N** [comment]
Perfect. Thank you.
